name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Atualizado para v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Atualizado para v3
        with:
          node-version: '20'  # Atualizado para a versão mais recente do Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
